services:

    blast_ui.twig.extensions.parameters:
        class: Blast\Bundle\UIBundle\Twig\Extensions\ParametersExtension
        arguments:
            - '%blast_ui%'
        tags:
            - { name: twig.extension }

    blast_ui.twig.extensions.breadcrumb:
        class: Blast\Bundle\UIBundle\Twig\Extensions\BreadcrumbExtension
        arguments:
            - '%blast_ui%'
            - '@blast_ui.twig.extensions.breadcrumb_builder'
        tags:
            - { name: twig.extension }

    blast_ui.twig.extensions.theme_handler:
        class: Blast\Bundle\UIBundle\Twig\Extensions\ThemeHandlerExtension
        arguments:
            - '@session'
            - '@request_stack'
            - '%blast_ui%'
        tags:
            - { name: twig.extension }

    blast_ui.twig.extensions.path_builder:
        class: Blast\Bundle\UIBundle\Twig\Extensions\PathBuilderExtension
        arguments:
            - '@router'
        tags:
            - { name: twig.extension }

    blast_ui.twig.extensions.access_property:
        class: Blast\Bundle\UIBundle\Twig\Extensions\AccessPropertyExtension
        tags:
            - { name: twig.extension }

    blast_ui.twig.extensions.display_data:
        class: Blast\Bundle\UIBundle\Twig\Extensions\DisplayDataExtension
        arguments:
            - '%blast_ui%'
        tags:
            - { name: twig.extension }

    blast_ui.twig.extensions.breadcrumb_builder:
        class: Blast\Bundle\UIBundle\Breadcrumb\BreadcrumbBuilder
        arguments:
            - '@router'

    blast_ui.twig.extensions.array_extension:
        class: Blast\Bundle\UIBundle\Twig\Extensions\ArraySortExtension
        tags:
            - { name: twig.extension }

    blast_ui.twig.extensions.url_tools:
        class: Blast\Bundle\UIBundle\Twig\Extensions\UrlToolsExtension
        arguments:
            - '@request_stack'
        tags:
            - { name: twig.extension }

    # WIDGETS

    blast_ui.twig.extensions.widgets:
        class: Blast\Bundle\UIBundle\Twig\Extensions\Widgets
        arguments:
            - '%blast_ui%'
        tags:
            - { name: twig.extension }

    
