services:

    sil.code_generator.manufacturing_bom:
        class: Sil\Component\Manufacturing\Generator\BomCodeGenerator

    sil.code_generator.manufacturing_order:
        class: Sil\Component\Manufacturing\Generator\ManufacturingOrderCodeGenerator


    ###################
    # DOMAIN SERVICE
    ###################

    sil.domain_service.manufacturing_order:
        class: Sil\Component\Manufacturing\Service\ManufacturingOrderService
        arguments:
            - '@sil.domain_service.stock_operation'
            - '@sil.domain_service.stock_movement'
            - '@sil.repository.stock_location'



    ###################
    # CONTROLLERS
    ###################

    sil.controller.manufacturing_order:
        class: Sil\Bundle\ManufacturingBundle\Controller\ManufacturingOrderCRUDController
        calls:
            - ['setContainer', ['@service_container']]
            - ['setManufacturingOrderService', ['@sil.domain_service.manufacturing_order']]
