Sil\Component\Manufacturing\Model\Bom:
    type: mappedSuperclass
    table: sil_manufacturing_bom
    fields:
        code:
            type: string(64)
            unique: true
            nullable: false
        qtyValue:
            type: decimal
            precision: 15
            scale: 5

    manyToOne:
        qtyUom:
            targetEntity: Sil\Bundle\UomBundle\Entity\Uom

            joinColumn:
                name: qty_uom_id
                referencedColumnName: id
                nullable: false
        stockItem:
            targetEntity: Sil\Component\Stock\Model\StockItemInterface
            joinColumn:
                name: stockitem_id
                referencedColumnName: id
                nullable: false

    oneToMany:
        lines:
          targetEntity: Sil\Component\Manufacturing\Model\BomLine
          mappedBy: bom
          cascade: ["remove", "persist"]
