imports:
    - { resource: '@SilUserBundle/Resources/config/vendor/blast/resource.yml' }
    - { resource: '@SilUserBundle/Resources/config/vendor/blast/menu.yml' }
    - { resource: '@SilUserBundle/Resources/config/vendor/blast/grids.yml' }
