imports:
    - { resource: "@PlatformBundle/Resources/config/services.yml" }

    # Vendors

    - { resource: "@PlatformBundle/Resources/config/vendor/stof.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/lexik.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/fos.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/doctrine.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/stfalcon.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/knp_paginator.yml" }

    # SIL Bundles

    - { resource: "@SilUserBundle/Resources/config/parameters.yml" }
    - { resource: "@SilUserBundle/Resources/config/app/config.yml" }

    - { resource: "@SilContactBundle/Resources/config/app/config.yml" }
    
    - { resource: "@SilProductBundle/Resources/config/app/config.yml" }

    # Blast

    - { resource: "@PlatformBundle/Resources/config/vendor/blast/csv_import.yml" }
    # - { resource: "@PlatformBundle/Resources/config/vendor/blast/dashboard.yml" }
    # - { resource: "@PlatformBundle/Resources/config/vendor/blast/search.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/blast/base_entities.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/blast/menu.yml" }
    # - { resource: "@PlatformBundle/Resources/config/vendor/blast/resource.yml" }
    # - { resource: "@PlatformBundle/Resources/config/vendor/blast/utils.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/blast/ui.yml" }
