services:

    blast.menu_loader:
        class: Blast\Bundle\MenuBundle\Configuration\Loader
        calls:
            - [setParameters, ['%blast_menu%']]
            - [setProfiler, ['@?blast_profiler.profiler.collector']]

    blast.menu_builder:
        class: Blast\Bundle\MenuBundle\Builder\MenuBuilder
        arguments: ["@knp_menu.factory"]
        calls:
            - [setTokenStorage, ['@security.token_storage']]
            - [setAuthorizationChecker, ['@security.authorization_checker']]
            - [setLoader, ['@blast.menu_loader']]

    blast.sidebar_menu.global:
        class: Knp\Menu\MenuItem
        factory: ["@blast.menu_builder", createGlobalSidebarMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: global_sidebar_menu }
