services:

### DOCTRINE EVENT LISTENERS ###

    # Canonicalization of emails and usernames
    sonata_sylius_user.listener.canonicalizer:
        class: Sil\Bundle\SonataSyliusUserBundle\EventListener\CanonicalizerListener
        # arguments:
        #     - "@sylius.canonicalizer"
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    # Traceable Doctrine mapping and behavior
    sonata_sylius_user.listener.traceable:
        class: Sil\Bundle\SonataSyliusUserBundle\EventListener\TraceableListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [setLogger,['@logger']]
            - [setTokenStorage, ['@security.token_storage']]
            - [setUserClass, ['%sil.model.user.class%']]
            - [setClassAnalyser, [Blast\Bundle\CoreBundle\Tools\Reflection\ClassAnalyzer]]

    # Ownable Doctrine mapping
    sonata_sylius_user.listener.ownable:
        class: Sil\Bundle\SonataSyliusUserBundle\EventListener\OwnableListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [setLogger,['@logger']]
            - [setTokenStorage, ['@security.token_storage']]
            - [setUserClass, ['%sil.model.user.class%']]
            - [setClassAnalyser, [Blast\Bundle\CoreBundle\Tools\Reflection\ClassAnalyzer]]

    # Set GUID primary keys for Sylius entities (and child classes)
    sonata_sylius_user.listener.sylius_guidable:
        class: Sil\Bundle\SonataSyliusUserBundle\EventListener\SyliusGuidableListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [setLogger, ['@logger']]
            - [setClassAnalyser, [Blast\Bundle\CoreBundle\Tools\Reflection\ClassAnalyzer]]
