security:

    # ##########################################################################
    # ROLES
    # ##########################################################################

    role_hierarchy:

        ROLE_SONATA_ADMIN:
            - ROLE_USER

        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN

    # todo use with bcrypt
    encoders:
        Sil\Bundle\UserBundle\Entity\User: plaintext

    providers:
        sil_user.doctrine_provider:
            entity:
                class: SilUserBundle:User
                property: username

    # ##########################################################################
    # FIREWALLS
    # ##########################################################################

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        sil:
            anonymous: ~
            provider: sil_user.doctrine_provider
            form_login:
                login_path: sil_user_login
                check_path: sil_user_login_check
                failure_path: sil_user_login
                default_target_path: sil_user_homepage
                use_forward: false
                use_referer: true
            logout:
                path: sil_user_logout
                target: sil_user_login

    # ##########################################################################
    # ACCESS CONTROL
    # ##########################################################################

    access_control:

        - { path: "^/(css|images|js)", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%sil.url_prefix%/resetting", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%sil.url_prefix%/login$", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%sil.url_prefix%/login-check$", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%sil.url_prefix%.*", role: ROLE_USER }
