Sil\Bundle\ContactBundle\Entity\City:
    type: mappedSuperclass
    table: sil_contact_city
    repositoryClass: Sil\Bundle\ContactBundle\Repository\CityRepository
    lifecycleCallbacks: {  }

    fields:
        name:
            type: string(255)
            nullable: false
        postCode:
            type: string(255)
            nullable: false
        code:
            type: string(255)
            nullable: true

    oneToOne:
        country:
            targetEntity: Sil\Bundle\ContactBundle\Entity\Country
            joinColumn:
                name: country_id
            cascade: [persist]

        province:
            targetEntity: Sil\Bundle\ContactBundle\Entity\Province
            joinColumn:
                name: province_id
                onDelete: SET NULL
            cascade: [persist]
