Sil\Bundle\ContactBundle\Entity\Group:
    type: mappedSuperclass
    table: sil_contact_group
    repositoryClass: Sil\Bundle\ContactBundle\Repository\GroupRepository
    lifecycleCallbacks: {  }

    fields:
        name:
            type: string(255)
            nullable: false

    manyToMany:
        members:
            targetEntity: Sil\Component\Contact\Model\GroupMemberInterface
            mappedBy: groups
            cascade: [ persist]
