blast_utils.choice.add:
    path:     blast/ajax/choices/add
    defaults: { _controller: BlastUtilsBundle:Choice:addChoice }

blast_utils.unique_field.check_availability:
    path: blast/ajax/unique/check
    defaults: { _controller: BlastUtilsBundle:UniqueField:checkAvailability }

blast_utils.custom_filters.save:
    path: blast/customFilters/save
    defaults: { _controller: BlastUtilsBundle:CustomFilters:saveFilter }

blast_utils.custom_filters.delete:
    path: blast/customFilters/delete
    defaults: { _controller: BlastUtilsBundle:CustomFilters:deleteFilter }
