sil_product_attribute_create:
    path:     /create
    defaults: { _controller: sil_product.controller.attribute:createAction }

sil_product_attribute_show:
    path:     /{attributeId}/show
    defaults: { _controller: sil_product.controller.attribute:showAction }
    requirements:
        attributeId: '^\{?[a-f\d]{8}-(?:[a-f\d]{4}-){3}[a-f\d]{12}\}?$'

sil_product_attribute_edit:
    path:     /{attributeId}/edit
    defaults: { _controller: sil_product.controller.attribute:editAction }
    requirements:
        attributeId: '^\{?[a-f\d]{8}-(?:[a-f\d]{4}-){3}[a-f\d]{12}\}?$'
