[template]
src = "parameters.yml.tmpl"
dest = "app/config/parameters.yml"
keys = [
       "/symfony/addr",
       "/symfony/env",
       "/postgres/hostname",
       "/postgres/user/dbname",
       "/postgres/user/username",
       "/postgres/user/password",
       "/elastic/hostname",
       "/elastic/indexalias",
]
