imports:
    - { resource: '@SilManufacturingBundle/Resources/config/vendor/blast/resource.yml' }
  #  - { resource: '@SilManufacturingBundle/Resources/config/vendor/blast/menu.yml' }

doctrine:
    orm:
        mappings:
            SilManufacturingBundle:
                type: yml
                prefix: Sil\Component\Manufacturing\Model
                dir: Resources/config/doctrine

        resolve_target_entities:
            Sil\Component\Stock\Model\StockItemInterface:                Sil\Component\Stock\Model\StockItem
            Sil\Component\Stock\Model\BatchInterface:                    Sil\Component\Stock\Model\Batch
            Sil\Component\Stock\Model\PartnerInterface:                  Sil\Component\Stock\Model\Partner

            Sil\Component\Stock\Repository\StockUnitRepositoryInterface:  Sil\Bundle\StockBundle\Doctrine\ORM\StockUnitRepository
