sil_contact_address_create:
    path:     /create
    defaults: { _controller: sil_contact.controller.address:createAction }

sil_contact_address_edit:
    path:     /edit/{id}
    defaults: { _controller: sil_contact.controller.address:editAction }

sil_contact_address_show:
    path:     /show/{id}
    defaults: { _controller: sil_contact.controller.address:showAction }

sil_contact_address_delete:
    path:     /delete/{id}
    defaults: { _controller: sil_contact.controller.address:deleteAction }

sil_contact_address_contact-address-list:
    path:     /contact-address-list/{contactId}
    defaults: { _controller: sil_contact.controller.address:getAddressListForContactAction }
