sil_contact_group_create:
    path:     /create
    defaults: { _controller: sil_contact.controller.group:createAction }

sil_contact_group_edit:
    path:     /edit/{id}
    defaults: { _controller: sil_contact.controller.group:editAction }

sil_contact_group_show:
    path:     /show/{id}
    defaults: { _controller: sil_contact.controller.group:showAction }

sil_contact_group_delete:
    path:     /delete/{id}
    defaults: { _controller: sil_contact.controller.group:deleteAction }

sil_contact_group_list:
    path:     /list
    defaults: { _controller: sil_contact.controller.group:listAction }

sil_contact_group_contact-group-list:
    path:     /contact-group-list/{contactId}
    defaults: { _controller: sil_contact.controller.group:getGroupListForContactAction }
