Sil\Component\Stock\Model\Movement:
    type: mappedSuperclass
    table: sil_stock_movement
    repositoryClass: Sil\Bundle\StockBundle\Doctrine\ORM\MovementRepository
    fields:
        code:
            type: string(64)
            unique: true
            nullable: false
        expectedAt:
            type: datetime
        completedAt:
            type: datetime
            nullable: true
        qtyValue:
            type: decimal
            precision: 15
            scale: 5
        stateValue:
            type: string(64)

    manyToOne:
        stockItem:
            targetEntity: Sil\Component\Stock\Model\StockItemInterface
            joinColumn:
                name: stockitem_id
                referencedColumnName: id
                nullable: false
        qtyUom:
            targetEntity: Sil\Bundle\UomBundle\Entity\Uom
            joinColumn:
                name: qty_uom_id
                referencedColumnName: id
                nullable: false
        operation:
            targetEntity: Sil\Component\Stock\Model\Operation
            inversedBy: movements
            joinColumn:
                name: operation_id
                referencedColumnName: id
                nullable: true
        srcLocation:
            targetEntity: Sil\Component\Stock\Model\Location
            joinColumn:
                name: location_src_id
                referencedColumnName: id
                nullable: true
        destLocation:
            targetEntity: Sil\Component\Stock\Model\Location
            joinColumn:
                name: location_dest_id
                referencedColumnName: id
                nullable: true
        batch:
            targetEntity: Sil\Component\Stock\Model\BatchInterface
            joinColumn:
                name: batch_id
                referencedColumnName: id
                nullable: true

    oneToMany:
        reservedStockUnits:
          targetEntity: Sil\Component\Stock\Model\StockUnit
          mappedBy: reservationMovement
