Sil\Bundle\StockBundle\Domain\Entity\Operation:
    type: mappedSuperclass
    repositoryClass: Sil\Bundle\StockBundle\Doctrine\ORM\OperationRepository
    fields:
        code:
            type: string(64)
            unique: true
            nullable: false
        typeValue:
            type: string(64)
            nullable: false
        expectedAt: 
            type: datetime
        completedAt: 
            type: datetime
            nullable: true
        stateValue:
            type: string(64)
    
    manyToOne:
        srcLocation: 
            targetEntity: Location   
            joinColumn:
                name: location_src_id
                referencedColumnName: id
                nullable: true
        destLocation: 
            targetEntity: Location
            joinColumn:
                name: location_dest_id
                referencedColumnName: id
                nullable: true
       
        partner: 
            targetEntity: PartnerInterface
            joinColumn:
                name: partner_id
                referencedColumnName: id
                nullable: true
    oneToMany:
        movements:
          targetEntity: Movement
          mappedBy: operation
          cascade: ["remove", "persist"]
    