Sil\Component\Stock\Model\Partner:
    type: mappedSuperclass
    table: sil_stock_partner
    repositoryClass: Sil\Bundle\StockBundle\Doctrine\ORM\PartnerRepository
    fields:
        fulltextName:
            type: string
