Sil\Component\Stock\Model\Warehouse:
    type: mappedSuperclass
    table: sil_stock_warehouse

    fields:
        name:
            type: string(255)
            nullable: false
        code:
            type: string(64)
            unique: true
            nullable: false

    oneToMany:
        locations:
          targetEntity: Sil\Component\Stock\Model\Location
          mappedBy: warehouse
