services:
    blast_search.hook.global_search_input:
        parent: blast_utils.hooks.abstract_hook
        class: Blast\Bundle\SearchBundle\Hook\GlobalSearchInput
        tags:
            - { name: blast.hook, hook: layout.global_search, template: BlastSearchBundle:Hook:globalSearchInput.html.twig }

    blast_search.twig.display_search_result_extension:
        class:  Blast\Bundle\SearchBundle\Twig\DisplaySearchResultExtension
        calls:
            - [setBlastSearchParameters, ['%blast_search%']]
        tags:
            - { name: twig.extension }

    blast_search.result.results_populator:
        class: Blast\Bundle\SearchBundle\Result\ResultsPopulator
        calls:
            - [setFosElasticaConfigManager, ['@fos_elastica.config_manager']]
            - [setDoctrine, ['@doctrine']]

    blast_search.search.global_search:
        class: Blast\Bundle\SearchBundle\Search\GlobalSearch
        calls:
            - [setFosElasticaClient, ['@fos_elastica.client']]
            - [setFosElasticaConfigManager, ['@fos_elastica.config_manager']]
            - [setResultsPopulator, ['@blast_search.result.results_populator']]
            - [setPaginator, ['@knp_paginator']]
