
services:
    sil_manufacturing.admin.bom:
        class: Sil\Bundle\ManufacturingBundle\Admin\BomAdmin
        arguments: [~, "%sil.model.manufacturing_bom.class%", BlastCoreBundle:CRUD]
        calls:
            - [ setBomCodeGenerator, ['@sil.code_generator.manufacturing_bom']]
            - [ setResourceRepository, ['@sil.repository.manufacturing_bom']]
            - [ setTemplates, [{show: SilManufacturingBundle:BomAdmin:show.html.twig,edit: SilStockBundle:CRUD:edit.html.twig,list: SilStockBundle:CRUD:list.html.twig}]]

        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Manufacturing
                label: sil.manufacturing.bom
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
