PlatformBundle\Entity\SilEcommerceBundle\ProductVariant:
    type: mappedSuperclass
    table: sil_ecommerce_product_variant

    manyToOne:
        uom:
            targetEntity: Sil\Bundle\UomBundle\Entity\Uom
            joinColumn:
                name: uom_id
                referencedColumnName: id
                nullable: true
        outputStrategy:
            targetEntity: Sil\Component\Stock\Model\OutputStrategy
            joinColumn:
                name: strategy_output_id
                referencedColumnName: id
                nullable: true
