PlatformBundle\Entity\SilMediaBundle\File:
    type: entity
    table: sil_media_file
    fields:
        path:
            type: string
            nullable: true
            unique: true
        type:
            type: string
            nullable: true
            unique: false
    # manyToOne:
    #     owner:
    #         targetEntity: Sil\Bundle\EcommerceBundle\Entity\ProductInterface
    #         inversedBy: images
