
services:
    sil_stock.admin.movement:
        class: Sil\Bundle\StockBundle\Admin\MovementAdmin
        arguments: [~, "%sil.model.stock_movement.class%", BlastCoreBundle:CRUD]
        calls:
            - [setMovementCodeGenerator, ['@sil.code_generator.stock_movement']]
            - [setResourceRepository, ['@sil.repository.stock_movement']]
            - [setStockItemQueries, ['@sil.domain_query.stock_item']]
            - [ setTemplates, [{show: SilStockBundle:CRUD:show.html.twig,edit: SilStockBundle:CRUD:edit.html.twig,list: SilStockBundle:CRUD:list.html.twig}]]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.movement
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
