
services:
    sil_stock.admin.location:
        class: Sil\Bundle\StockBundle\Admin\LocationAdmin
        arguments: [~, "%sil.model.stock_location.class%", BlastCoreBundle:CRUD]
        calls:
            - [setResourceRepository, ['@sil.repository.stock_location']]
            - [setStockUnitRepository, ['@sil.repository.stock_unit']]
            - [setStockItemRepository, ['@sil.repository.stock_item']]
            - [setStockItemQueries, ['@sil.domain_query.stock_item']]
            - [ setTemplates, [{show: SilStockBundle:CRUD:show.html.twig,edit: SilStockBundle:CRUD:edit.html.twig,list: SilStockBundle:CRUD:list.html.twig}]]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.location
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
