Blast\Bundle\UtilsBundle\Entity\CustomFilter:
    type: entity
    table: blast_custom_filter
    repositoryClass: Blast\Bundle\UtilsBundle\Repository\CustomFilterRepository
    blast:
        loggable:     true
    fields:
        name:
            type: string
            length: 255
        routeName:
            type: string
            length: 255
        routeParameters:
            type: text
            nullable: true
        filterParameters:
            type: text
            nullable: true
    manyToOne:
        user:
            targetEntity: Sil\Bundle\UserBundle\Entity\UserInterface
