
services:
    sil_ecommerce.admin.product_option_value:
        class: Sil\Bundle\EcommerceBundle\Admin\ProductOptionValueAdmin
        arguments: [~, "%sil.model.ecommerce_product_option_value.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommerce.menu_label.product_option_value
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
