
services:
    sil_ecommerce.admin.product_option:
        class: Sil\Bundle\EcommerceBundle\Admin\ProductOptionAdmin
        arguments: [~, "%sil.model.ecommerce_product_option.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommerce.menu_label.product_option
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
