imports:
    - { resource: "@SilUomBundle/Resources/config/vendor/blast/resource.yml" }


doctrine:
    orm:
        mappings:
            SilUomBundle:
                type: yml
                prefix: Sil\Bundle\UomBundle\Entity
                dir: Resources/config/doctrine
