services:
    sil.admin.product:
        class: PlatformBundle\Admin\ProductAdmin
        arguments: [~, "%sil.model.product.class%", "PlatformBundle:Product"]
        calls:
            - [setResourceRepository, ['@sil.repository.product']]
            - [setStockItemQueries, ['@sil.domain_query.stock_item']]
            - [setLocationRepository, ['@sil.repository.stock_location']]
            - [setStockUnitRepository, ['@sil.repository.stock_unit']]
            - [ setTemplates, [{show: SilStockBundle:StockItemAdmin:show.html.twig,edit: SilStockBundle:CRUD:edit.html.twig,list: SilStockBundle:CRUD:list.html.twig}]]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Produits
                label: sil.product
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
