services:
    sil_ecommerce.admin.product:
        class: PlatformBundle\Admin\ProductAdmin
        arguments: [~, "%sil.model.product.class%", "SilEcommerceBundle:ProductCRUD"]
        calls:
            - [ setTemplate, [ edit, SilEcommerceBundle:ProductAdmin:edit.html.twig ] ]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Produits
                label: sil.ecommerce.product
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
